config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates_presence_of :date, :rationale
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name

  def full_name_last_first
    last_name.upcase + ", " + first_name.upcase
  end

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update , :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new 
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to @post, notice: "Your post was successfully created."
    else
      render new_post_path
    end
  end

  def edit
  end

  def update
    if(@post.update(post_params))
      redirect_to @post, notice: "Your post was succesfully updated."
    else
      redirect_to edit_post_path, id: @post.id
    end
  end

  def show
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Your post was successfully deleted,"
  end
  
  private
  
  def post_params
    params.require(:post).permit(:date, :rationale)
  end

  private
  
    def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(path)
    if current_page?(path)
      "active"
    else
      ""
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"
      <div class="row">
        <div class="col-md-12">
          <%= render 'shared/nav' %>         
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-horizontal">
  <%= form_for @post do |f| %>

    <div class="form-group" %>
      <%= f.label :date, class: "col-sm-2 control-label" %>
      <%= f.date_field :date, class: "col-sm-2 form-control" %>
    </div>

    <div class="form-group" %>
      <%= f.label :rationale, class: "col-sm-2 control-label" %>
      <%= f.text_area :rationale, class: "form-control" %>
    </div>

    <%= f.submit 'Save', class: "btn btn-primary" %>

  <% end %>
</div>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.id %>
  </td>
  <td>
    <%= post.date %>
  </td>
  <td>
    <%= post.user.full_name_last_first %>
  </td>
  <td>
    <%= truncate(post.rationale) %>
  </td>
  <td>
    <%= link_to "Edit", edit_post_path(post), id: "edit_#{post.id}" %>
  </td>
  <td>
    <%= link_to "Delete", post_path(post), method: :delete, 
        id: "delete_post_from_index_#{post.id}", data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/posts/edit.html.erb
<h1>Edit Time Entry</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>
        #
      </th>
      <th>
        Date
      </th>
      <th>
        Employee
      </th>
      <th>
        Rationale
      </th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>
	

app/views/posts/new.html.erb
<h1>New Time Entry</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Show Post</h1>
<p>Posted on: <%= @post.date %></p>
<p>Rationale: <%= @post.rationale %></p>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>Overtime</h1> 
</div>

<div class="custom-nav">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link "+active(root_path) %>
    </li>
    <li class="nav-item">
      <%= link_to "Time Entries", posts_path, class: "nav-link "+active(posts_path)  %>
    </li>
    <li class="nav-item">
      <%= link_to "Add New Time Entry", new_post_path, class: 'nav-link', id: 'new_post_from_nav' %>
    </li>
    <li class="nav-item dropdown ml-md-auto">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "Edit Details", edit_user_registration_path, class: "dropdown-item" %>
        <div class="dropdown-divider">
        </div> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
      </div>
    </li>
  </ul>
</div>